### ISSUE TITLE
Can this component be handled that a user can't close the alert?

### ISSUE THREAD

**Issue by jjdp** [devBrian/react-native-dropdownalert#24]
so only code close is possible.
i have read that you can do `closeInterval={0}` but can you also set the cancelBtnImageSrc to `null` without errors? and also disable tap to close?

I haven't tested this component yet.

**Comment by devBrian** [comment]
Hi @jjdp  

The `closeInterval={0}` will keep it open until action is taken either by pan gesture up or cancel button or tap the alert. But this also raises a question in which **can the the alert be without a user action?** No, because `onPress` will default to an action and pan gesture responders have no case to be disabled. I think maybe a prop like `userInteractionEnabled={false}` might address. I am going to add this. 

Sorry for the delay. Hope this helps.

**Comment by devBrian** [comment]
Hi @jjdp again

I added 2 new props `tapToCloseEnabled` and `panResponderEnabled` to satisfy the ability to disable user interaction for close. Also, `showCancel` should be false. 

Hope this helps.
